version: "3"
services:
  mongo-test:
    image: mongo
    container_name: my-mongo-container-test
    ports:
      - "27017:27017"
    volumes:
      - mongo-test-data:/data/database

volumes:
  mongo-test-data:
